### ISSUE TITLE
Add a `isFunction` function

### ISSUE THREAD

**Issue by mitchellporter** [eggheadio-github/stack-overflow-copy-paste#100]
Thanks for putting together the [How to Contribute to an Open Source Project on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) course @kentcdodds.

I'd like to add a simple function which checks if a given value is a function eg. `isFunction(value)`, using this stackoverflow answer: https://stackoverflow.com/a/7356528/3344977

Thanks.

**Comment by kentcdodds** [comment]
Sounds like a great idea! Let's do it :)
