### ISSUE TITLE
Add isEven function

### ISSUE THREAD

**Issue by GeoDoo** [eggheadio-github/stack-overflow-copy-paste#101]
Hi Kent and contributors,

I'd like to add a simple function which checks if a given number is Even eg. isEven(n), using this stackoverflow answer: https://stackoverflow.com/questions/16929958/how-to-determine-if-a-number-is-odd-or-even-in-java-script 

The function will be this: 

```
function isEven(n) {
  return n == parseFloat(n) && !(n % 2);
}

```

Thanks in advance for the great opportunity to learn and excuse my ignorance! I am a newcomer.

**Comment by kentcdodds** [comment]
Sounds perfect! I'm looking forward to your pull request!
