### ISSUE TITLE
issue with npm install

### ISSUE THREAD

**Issue by SoxFace** [eggheadio-github/stack-overflow-copy-paste#11]
Hi there, 

Really enjoying and learning loads from your video tutorial. I'm stuck on video #8 when I run the test and build:

```
stack-overflow-copy-paste $ npm t && npm run build
> stack-overflow-copy-paste@0.0.0-semantically-released test /Users/sonyacorcoran/Projects/stack-overflow-copy-paste
> ava --require babel-register

sh: ava: command not found
npm ERR! Test failed.  See above for more details.
```

Any ideas?

**Comment by kentcdodds** [comment]
Hi @SoxFace! That error would seem to indicate that you haven't installed `ava`. Make sure you run `npm install`.

**Comment by SoxFace** [comment]
Thanks for the prompt response @kentcdodds.

I've ran npm install and it told me to tell you...

```
Failed at the stack-overflow-copy-paste@0.0.0-semantically-released test:watch script 'nodemon --exec npm t'.
npm ERR! This is most likely a problem with the stack-overflow-copy-paste package,
npm ERR! not with npm itself.
**npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec npm t**
```

**Comment by kentcdodds** [comment]
Can you give me any more of the output you're seeing?

**Comment by SoxFace** [comment]
Thanks for your time Kent - I ran the following and the tests are now passing, I'll get back to the learning.

$ rm -rf node_modules/
$ npm cache clean
$ npm install

Thanks again for your generosity with your time and knowledge, it's amazing.

**Comment by kentcdodds** [comment]
Glad you got it working!
