### ISSUE TITLE
Add a max function

### ISSUE THREAD

**Issue by mis101bird** [eggheadio-github/stack-overflow-copy-paste#114]
Hi, 
Thanks for the awesome open source contribution tutorial. This is my first time to contribute the code.
I would like to add `max` function to get the maximum value of an array, and the implementation is showed below.
```
function __getMax(max, value) {
    if(value > max){
    	max=num;
    }
    return max;
}

function max(array){
    array.reduce(__getMax);
}
```
I hope I could contribute this issue  :)

**Comment by kentcdodds** [comment]
Sounds perfect! I'm looking forward to seeing your PR @mis101bird! :clap:
