### ISSUE TITLE
Add a findCube function

### ISSUE THREAD

**Issue by akoliyot** [eggheadio-github/stack-overflow-copy-paste#117]
I recently watched your contributing to open source series on Egghead. Thank you for that, Kent! 
For my first contribution I was thinking if I could add a function to find the cube of a number. What do you think?

**Comment by kentcdodds** [comment]
Sounds just fine! Thanks @akoliyot! Make sure to follow the instructions in the CONTRIBUTING.md file :)

**Comment by ojas1234** [comment]
Yes.. I will

**Comment by akoliyot** [comment]
Sure, thanks Kent 👍
