### ISSUE TITLE
Slugify function

### ISSUE THREAD

**Issue by codejockie** [eggheadio-github/stack-overflow-copy-paste#120]
Hi, @kentcdodds I saw your course on contributing to open source, so I took a dive in.
I would like to add the slugify function from this answer https://stackoverflow.com/questions/1053902/how-to-convert-a-title-to-a-url-slug-in-jquery

**Comment by kentcdodds** [comment]
Sounds great!

**Comment by codejockie** [comment]
Hi @kentcdodds I wrote a test for the function and running it throws this error:   

```
1. slugify › slugifies a text
   failed with "(0 , _src.slugify) is not a function"
      Test.fn (slugify.test.js:7:18)
    _combinedTickCallback (internal/process/next_tick.js:73:7)
    process._tickCallback (internal/process/next_tick.js:104:9)
```

Any idea on this?

**Comment by kentcdodds** [comment]
Yeah, make sure that you're importing and exporting it the same way the others do in src/index.js 😀

**Comment by codejockie** [comment]
Thank you.

**Comment by codejockie** [comment]
I'm done with the feature. I ran `npm run commit` and I get this `Denote the scope of this change ($location, $browser, $compile, etc.):`. What do I put there?
