### ISSUE TITLE
Add a Fibonacci function

### ISSUE THREAD

**Issue by bhankee** [eggheadio-github/stack-overflow-copy-paste#132]
Excited to have my first open source contribution! I believe this needs a function that satisfies the Fibonacci formula.

**Comment by kentcdodds** [comment]
Sounds perfect!

**Comment by ravikishorethella** [comment]
@bhankee @kentcdodds  Is anyone working on this? It's been quite some time and is still open so, I thought of asking you both whether I can work on this or not. Thanks!

**Comment by kentcdodds** [comment]
Feel free 👍

**Comment by ravikishorethella** [comment]
@kentcdodds should the function return an array of numbers or the sum of the numbers ?

**Comment by kentcdodds** [comment]
Hi @ravikishorethella, sorry for the delay, I was on a family trip. Let's have it just return the sum of the numbers :+1:

**Comment by ravikishorethella** [comment]
@kentcdodds no problem!!! Thanks for the information.
