### ISSUE TITLE
Convert first letter of a string to a Capital letter

### ISSUE THREAD

**Issue by oyin-k** [eggheadio-github/stack-overflow-copy-paste#142]
Hello Kent i got to this repo through your course on egghead and this would be my first contribution in terms of submitting a pull request to open source. 
I want to add a function that converts the first letter of a string to a capital letter. Thanks.
Gotten from the first answer here: https://stackoverflow.com/questions/1026069/how-do-i-make-the-first-letter-of-a-string-uppercase-in-javascript

**Comment by kentcdodds** [comment]
Looks super! I look forward to the PR! :)

**Comment by oyin-k** [comment]
Sorry kent  need some help. I dont know how to write a test for the function. how do i go about that. New to it.

**Comment by kentcdodds** [comment]
That's fine @oyin-k.

So you can create a file in the `test` directory that's the same as the file you created for the implementation, then you `import` the implementation and write out a few tests. You can see [the flatten implementation](https://github.com/eggheadio-github/stack-overflow-copy-paste/blob/578e50ee314a50e48e47fbdcc83dfc37444d2a70/src/flatten.js) and [the flatten tests](https://github.com/eggheadio-github/stack-overflow-copy-paste/blob/578e50ee314a50e48e47fbdcc83dfc37444d2a70/test/flatten.test.js) as an example of how to do this.

Then you'll also want to make sure you add your implementation to [this file](https://github.com/eggheadio-github/stack-overflow-copy-paste/blob/578e50ee314a50e48e47fbdcc83dfc37444d2a70/src/index.js) as well. You add an import and add it to the export.

If the ES Module syntax is unfamiliar to you, you can [watch this](https://www.youtube.com/watch?v=t3R3R7UyN2Y&t=1h44m19s) to learn more about them.

Good luck!

**Comment by kentcdodds** [comment]
Oh, and as a basic intro to what a test is, you might like this blog post I just published yesterday: http://kcd.im/whats-a-test

**Comment by oyin-k** [comment]
ok right to it. thanks

**Comment by oyin-k** [comment]
Hello kent. thanks for yesterday. i made a push and for some reason i am not seeing it. i went to compare across forks as you taught but what i am seeing is this "eggheadio-github:master and oyin-k:pr/capitalizeFirstLetter are identical". thanks for the help.

**Comment by oyin-k** [comment]
i kept trying and now its giving me a load of npm errors

**Comment by kentcdodds** [comment]
Hmmm... Would you mind copy/pasting everything you're seeing?

**Comment by oyin-k** [comment]
no problem this is it:

C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste>git commit -m "feat(capitalizeFirstLetter): add 'capitalizeFirstLetter' function (#142)

> stack-overflow-copy-paste@0.0.0-semantically-released validate C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste
> npm-run-all lint test build


> stack-overflow-copy-paste@0.0.0-semantically-released lint C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste
> eslint src/


> stack-overflow-copy-paste@0.0.0-semantically-released test C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste
> cross-env NODE_ENV=test nyc ava --concurrency 5

C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\node_modules\nyc\node_modules\rimraf\rimraf.js:195
      throw er
      ^

Error: EPERM: operation not permitted, lstat 'C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\.nyc_output'
    at Object.fs.lstatSync (fs.js:941:11)
    at Function.rimrafSync [as sync] (C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\node_modules\nyc\node_modules\rimraf\rimraf.js:290:24)
    at NYC.cleanup (C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\node_modules\nyc\index.js:319:36)
    at NYC.reset (C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\node_modules\nyc\index.js:333:8)
    at Object.<anonymous> (C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste\node_modules\nyc\bin\nyc.js:48:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stack-overflow-copy-paste@0.0.0-semantically-released test: `cross-env NODE_ENV=test nyc ava --concurrency 5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stack-overflow-copy-paste@0.0.0-semantically-released test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oyin-k.saintscommunity\AppData\Roaming\npm-cache\_logs\2018-01-03T10_49_45_226Z-debug.log
ERROR: "test" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stack-overflow-copy-paste@0.0.0-semantically-released validate: `npm-run-all lint test build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stack-overflow-copy-paste@0.0.0-semantically-released validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oyin-k.saintscommunity\AppData\Roaming\npm-cache\_logs\2018-01-03T10_49_45_324Z-debug.log

C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste>git push --no-verify
Everything up-to-date

**Comment by kentcdodds** [comment]
That's odd. What's happening is when `rimraf` attempts to delete the `.nyc_output` directory, it's failing. I'm not sure why what's happening. But try creating that directory in the root of the project. If it already exists, try deleting it. Then run `npm run test` and see what happens.

What you made was great though so I merged it. Thanks!
