### ISSUE TITLE
Add 'swapElements' function

### ISSUE THREAD

**Issue by turisap** [eggheadio-github/stack-overflow-copy-paste#151]
Hi Kent, great course!

This is my first attempt to contribute, so I'd like to implement `swapElements()` function which would swap two given elements in an array.  Please let me know if this can be done.

**Comment by kentcdodds** [comment]
Awesome! That sounds like a great contribution :+1:

**Comment by kentcdodds** [comment]
Good job on #152!

**Comment by turisap** [comment]
Thank you Kent for a great opportunity to learn how to contribute!
