### ISSUE TITLE
Add a function that retrieves query string values

### ISSUE THREAD

**Issue by dominictwlee** [eggheadio-github/stack-overflow-copy-paste#160]
Hi Kent, thank you so much for helping us newbies get our feet wet in open source! 

I'd like to add a function that retrieves query string values.

[https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript/901144#901144](https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript/901144#901144)

**Comment by kentcdodds** [comment]
Looks super! Thanks @dominictwlee!
