### ISSUE TITLE
Remove accents/diacritics in a string

### ISSUE THREAD

**Issue by archemiro** [eggheadio-github/stack-overflow-copy-paste#161]
Hi Kent, awesome project.

Seems like it would be useful to have a `removeAccents` function and there is none implemented. If you are interested in this function let me know and I'll be glad to make a PR based on [this stackoverflow thread](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript/37511463).

**Comment by kentcdodds** [comment]
Sure! Thanks!

**Comment by archemiro** [comment]
Hi Kent, thanks for your support and for pushing OSS! The PR is done!
