### ISSUE TITLE
Add a function that truncates a string

### ISSUE THREAD

**Issue by sosmaniac-FCC** [eggheadio-github/stack-overflow-copy-paste#164]
Thank you Kent for creating this tutorial environment. May I work on a function that truncates a string?
Inspiration: https://stackoverflow.com/questions/1301512/truncate-a-string-straight-javascript 
Something along the lines of: 
```javascript
function (target, length) {
    // return the string parameter 'target' truncated by the amount of the integer parameter 'length'
}
```

**Comment by kentcdodds** [comment]
Sounds super! :+1:
