### ISSUE TITLE
Add 'occurrences' function

### ISSUE THREAD

**Issue by lwd369** [eggheadio-github/stack-overflow-copy-paste#186]
Hi Kent. Thank you for creating this awesome course on egghead.io!

I wanna add a function to count string occurrence in string. And this will be my first pull request, hope to be a good beginning .

  reference:[https://stackoverflow.com/questions/4009756/how-to-count-string-occurrence-in-string](url)

**Comment by kentcdodds** [comment]
Sounds great!

**Comment by lwd369** [comment]
Wow! My first PR has been merged, thank you, Kent!
