### ISSUE TITLE
Add Text Justification

### ISSUE THREAD

**Issue by Jonathan-Montanez** [eggheadio-github/stack-overflow-copy-paste#195]
Hi Kent, thanks for such great course. Id like to contribute by adding a text justification program which will basically work by adding white space between words in sentence. Thanks in advance for allowing me to contribute if possible.

**Comment by kentcdodds** [comment]
Sure! Sounds great :)

**Comment by Jonathan-Montanez** [comment]
I need help!
What do you mean by:
"If you can't or need help then commit what you have with --no-verify and make a PR"

**Comment by Jonathan-Montanez** [comment]
Do you mean set --no-verify as the commit message?
