### ISSUE TITLE
add removeProperty()

### ISSUE THREAD

**Issue by jedilancey** [eggheadio-github/stack-overflow-copy-paste#196]
Hi Kent,
I'd like to add a removeProperty() function as described here:
https://stackoverflow.com/questions/208105/how-do-i-remove-a-property-from-a-javascript-object
Thanks for the great tutorial.

**Comment by kentcdodds** [comment]
Sure!

**Comment by jedilancey** [comment]
Thank you for merging my PR.
#197 closes this issue right?

**Comment by kentcdodds** [comment]
Yep! Thanks!
