### ISSUE TITLE
Function DecToHex

### ISSUE THREAD

**Issue by EstebanMarin** [eggheadio-github/stack-overflow-copy-paste#201]
Hey @kentcdodds loved the Egghead course and wanted to start with something simple. 

Want to create a a Simple [DecToHex](https://stackoverflow.com/questions/57803/how-to-convert-decimal-to-hex-in-javascript) function and pass through the first process of commiting to OSS.

Thanks!

**Comment by kentcdodds** [comment]
Sounds great! Please do!

**Comment by EstebanMarin** [comment]
This can be closed by[#202](https://github.com/eggheadio-github/stack-overflow-copy-paste/pull/202)
