### ISSUE TITLE
Random dice roll

### ISSUE THREAD

**Issue by kriyeng** [eggheadio-github/stack-overflow-copy-paste#205]
Hi Kent,
Congratulations and thank you for your course!
I would like to add roll dice functionality to your project.

https://stackoverflow.com/questions/15603217/random-dice-nr-javascript

**Comment by kentcdodds** [comment]
Sure! Sounds great!

**Comment by kentcdodds** [comment]
Someone's implemented this. Feel free to suggest something else :)
