### ISSUE TITLE
Add `copyArrayByValue` function

### ISSUE THREAD

**Issue by mancristiana** [eggheadio-github/stack-overflow-copy-paste#213]
Hi Kent! Thanks for the informative course on egghead and all the amazing resources you are making 👍 ! 

I want to try adding a `copyArrayByValue` function as described in this StackOverflow answer: 
https://stackoverflow.com/a/7486130/5679427

**Comment by kentcdodds** [comment]
Sounds great!

**Comment by mancristiana** [comment]
Created a PR!
