### ISSUE TITLE
Add a mode function

### ISSUE THREAD

**Issue by anddago** [eggheadio-github/stack-overflow-copy-paste#221]
:wave:
First of all, thank you for your inspiring lessons on open source contribution!
I would like to add a `mode` function: it will return the most common element in an array. 
The solution I found on StackOverflow: [Get the element with the highest occurrence in an array
](https://stackoverflow.com/a/1053865)
Would it be ok?

**Comment by kentcdodds** [comment]
Sure! Sounds great!
