### ISSUE TITLE
Can we add a largest function

### ISSUE THREAD

**Issue by AkashRajpurohit** [eggheadio-github/stack-overflow-copy-paste#228]
I wanted to add a largest function which will return the largest value in the array

```javascript
const array = [290,452,575,235]
const largestItem = largest(array) // 575
```

**Comment by AkashRajpurohit** [comment]
The stackoverflow link would be this: https://stackoverflow.com/a/1379556/9713990

**Comment by kentcdodds** [comment]
Sounds great!
