### ISSUE TITLE
New Maintainer Needed

### ISSUE THREAD

**Issue by kentcdodds** [eggheadio-github/stack-overflow-copy-paste#243]
I've loved having this repo as a safe place for people to contribute to open source for the first time. We have 95 contributors to the project! That's amazing when you think that for most of these people it was their first open source contribution and I've seen several of the contributors around GitHub contributing to other projects and it's been an awesome experience.

However, my plate has been filling up rapidly and I need to cut out some things to make room. So I've decided this project needs to no longer take my time. It would be a shame for this project to stop serving people though so I'd like to see whether anyone would like to pick it up and keep it going.

A maintainer of this project doesn't have to do a whole lot. You don't even need to bother publishing it to npm because that's not what this project is about. And because this project follows my [How to Contribute to an Open Source Project on GitHub](http://kcd.im/pull-request) course on Egghead.io, you wont need to keep dependencies updated or change really anything about the project because we want it to stay aligned with what people are watching in the course.

So what does a maintainer need to do?

- Respond to issues
- Work with people in pull requests

And of course do all of this with the warmth and friendliness needed by someone new to open source.

And we don't have to have just one maintainer either. We could easily have multiple maintainers of this project. If you're interested in helping, please comment here!

**Comment by aravindc15** [comment]
I would really like to contribute but I have not contributed previously and not sure where to start..Is it fine if have not contributed previously

**Comment by krvajal** [comment]
I am interested in becoming a mantainer

**Comment by Yusadolat** [comment]
Hi @kentcdodds lets do this!

**Comment by technicius** [comment]
Would love to contribute

**Comment by abhimanyusingh** [comment]
I am interested too

**Comment by mintuz** [comment]
Hello 👋, I'm interested.

**Comment by OlivierJM** [comment]
I would love to help on this.

**Comment by bamoha** [comment]
I am interested in this.

**Comment by kentcdodds** [comment]
Wonderful! For those who are interested, go ahead and [watch the repo](https://github.com/eggheadio-github/stack-overflow-copy-paste/watchers) and help people be successful in making an open source pull request.

Remember:

- It's more important that they get it merged than the code is right. I don't even care if the code works correctly so long as the build passes.
- Please be patient. Some people can't respond right away.
- Try to avoid letting people take other's issues. Have people file their own issues.

**Very important**: If you have not watched the course yet, please do so before you do anything else: http://kcd.im/pull-request

I'll keep an eye on the repo for a while then I'll hand contributor rights to those I see helping out :) Thanks!

**Comment by bolah2009** [comment]
Cool, going through your course and found this! **Am interested** and also making my first PR here (hopefully). _I am watching the repo !_

**Comment by kentcdodds** [comment]
See #257
