### ISSUE TITLE
Sort array of objects by string property value

### ISSUE THREAD

**Issue by kelvinatorr** [eggheadio-github/stack-overflow-copy-paste#28]
Can I add the dynamicSort function?

[http://stackoverflow.com/questions/1129216/sort-array-of-objects-by-string-property-value-in-javascript/4760279#4760279](http://stackoverflow.com/questions/1129216/sort-array-of-objects-by-string-property-value-in-javascript/4760279#4760279)

The one in the answer with 377 upvotes.

**Comment by kentcdodds** [comment]
Looks good to me! Good luck :D
