### ISSUE TITLE
Add isArray to check if an object is a javascript array

### ISSUE THREAD

**Issue by rheaditi** [eggheadio-github/stack-overflow-copy-paste#38]
Hi :innocent: 

I'd like to add an `isArray( someObject)` method that returns `true`/`false` based on whether the object `someObject` is a javascript array. 

From [this](http://stackoverflow.com/a/4775737) answer :)
Also, based on [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Polyfill) polyfill.

Thanks
\- first timer

**Comment by kentcdodds** [comment]
Awesome! Note, in the Contributing guidelines:

> In the case of adding a new function, that function must:
> - NOT add anything to the prototype of built-in objects (one of StackOverflow's favorite things to do)

So, you can still implement this function, you'll just need to adjust it so it doesn't modify `Array`

Thanks! Looking forward to seeing your pull request! Let me know if you need any help 😄

**Comment by kentcdodds** [comment]
This was resolved a while back :)
