### ISSUE TITLE
Add a hex2rgb function

### ISSUE THREAD

**Issue by victoraugust** [eggheadio-github/stack-overflow-copy-paste#43]
Hi, 
I would like to add a new `hex2rgb` function, which can convert color in Hex to RGB format. Original solution on [StackOverflow](http://stackoverflow.com/a/12342275). 

Would it be okay? :)

**Comment by kentcdodds** [comment]
Sounds great! Let me know if you need help :)

**Comment by victoraugust** [comment]
contributing is kinda fun. :p

**Comment by kentcdodds** [comment]
I agree! Thanks for your contribution!
