### ISSUE TITLE
Add an isNullOrWhitespace function

### ISSUE THREAD

**Issue by aleury** [eggheadio-github/stack-overflow-copy-paste#45]
I'd like to practice contributing by adding a function that checks if a string is null or only consists of white space. It comes in handy every now and then. Here's an example on [StackOverflow](http://stackoverflow.com/questions/5559425/isnullorwhitespace-in-javascript).

**Comment by kentcdodds** [comment]
Awesome! Let's do it. I suggest this answer: http://stackoverflow.com/a/32800728/971592
