### ISSUE TITLE
padLeft needed

### ISSUE THREAD

**Issue by silvestertomato** [eggheadio-github/stack-overflow-copy-paste#5]
I really really really want to have a `padLeft` function here. Anyone wanna work on that?

**Comment by kentcdodds** [comment]
I'd like to help out with this issue. Is there a specific implementation you had in mind?

**Comment by silvestertomato** [comment]
Awesome @kentcdodds! I'd love the help. Thanks.

> Is there a specific implementation you had in mind?

Not in particular, could you find and suggest an implementation you find on StackOverflow?

**Comment by kentcdodds** [comment]
Sure! How about this one? Seems simple enough, follows the standards in the CONTRIBUTING.md, and gets the job done: http://stackoverflow.com/a/34083277/971592

```javascript
function padLeft(str,size,padwith) {
	if(size <= str.length) {
		return str;
	} else {
		return Array(size-str.length+1).join(padwith||'0')+str
	}
}
```

**Comment by silvestertomato** [comment]
Looks great! Let me know if there's anything I can do to help :+1:

**Comment by kentcdodds** [comment]
Will do! Thanks!
