### ISSUE TITLE
Add a removeDuplicates function

### ISSUE THREAD

**Issue by ccabrales** [eggheadio-github/stack-overflow-copy-paste#52]
I got here after watching your Open Source Contribution course and want to try my first pull request. Thanks for the great guide!

I would like to add a `removeDuplicates` function that will remove all the duplicate values in an array. Here is the original solution on [StackOverflow](http://stackoverflow.com/a/18328062)

**Comment by kentcdodds** [comment]
Perfect! I look forward to seeing your solution!
