### ISSUE TITLE
Add an `add` function

### ISSUE THREAD

**Issue by kentcdodds** [eggheadio-github/stack-overflow-copy-paste#55]
So I can add numbers together: `add(1, 2) === 3`

**Comment by kentcdodds** [comment]
Honestly, you'll likely not be able to find a StackOverflow answer for this. Don't worry about that for this one :)

**Comment by valishah** [comment]
Hi @kentcdodds . I would like to help on this. May i know your expectations ? 

I'm just thinking something like this. 

`function add(num1, num2) {
  return num1+num2 
}`

Correct me if i'm wrong and suggest the requirement.

**Comment by kentcdodds** [comment]
Thanks for the pull request!

**Comment by valishah** [comment]
Thanks to you for helping on these practices. I have gone through video series and everything worked out great.
