### ISSUE TITLE
Add `multiply` function

### ISSUE THREAD

**Issue by kentcdodds** [eggheadio-github/stack-overflow-copy-paste#57]
So I can multiply two numbers: `multiply(3, 4) === 12`

**Comment by kentcdodds** [comment]
Honestly, you'll likely not be able to find a StackOverflow answer for this. Don't worry about that for this one :)

**Comment by emilkloeden** [comment]
Hi @kentcdodds , can I try taking this one?

**Comment by kentcdodds** [comment]
Sure!

**Comment by emilkloeden** [comment]
Thanks! I'll get onto it tonight when I get back from work :) (Australia
and timezones ;))

**Comment by shubham808** [comment]
i am new this would be my first issue i think i want to try this one

**Comment by kentcdodds** [comment]
Someone already took this one, but perhaps you could create a `square` function which will evaluate the square of the given argument.

**Comment by shubham808** [comment]
i will thanks!
