### ISSUE TITLE
Make flatten deep flatten

### ISSUE THREAD

**Issue by silvestertomato** [eggheadio-github/stack-overflow-copy-paste#6]
Right now:

``` javascript
const array = [1, 2, [3, 4, [5, 6], 7], 8]
flatten(array) // [1, 2, 3, 4, [5, 6], 7, 8]
```

What I want

``` javascript
const array = [1, 2, [3, 4, [5, 6], 7], 8]
flatten(array) // [1, 2, 3, 4, 5, 6, 7, 8]
```

**Comment by Shenseye** [comment]
Add a test for this. #12

**Comment by kentcdodds** [comment]
Fantastic! For some reason I thought this would be a breaking change. Didn't realize it was already supported. Thanks for the test!

**Comment by diwesh87** [comment]
Hi, I am trying to go through your course "How to contribute to an Open Source Project on Github" . I would like to add the function to "find duplicates items in an array". The original solution is here at [Find duplicate items in an array](http://stackoverflow.com/questions/840781/easiest-way-to-find-duplicate-values-in-a-javascript-array)

**Comment by kentcdodds** [comment]
Cool could you create a new issue for this? I like this answer a lot personally :-) http://stackoverflow.com/a/24968449/971592
Once you have the new issue created, please feel free to get started!
