### ISSUE TITLE
Linkify Egghead.io

### ISSUE THREAD

**Issue by silvestertomato** [eggheadio-github/stack-overflow-copy-paste#7]
On the README, I'd like Egghead.io to be linked!

**Comment by simplydallas** [comment]
It appears that commit 5e119fc75ea96178a907c5dfa530863549b61c24 already handled this.

**Comment by kentcdodds** [comment]
Ah, you are correct. Thanks! If you're interested in practicing by implementing, feel free to let me know in the issues :-)
