### ISSUE TITLE
Add isToday function

### ISSUE THREAD

**Issue by migalmeida** [eggheadio-github/stack-overflow-copy-paste#71]
Hi, 

After watching your very useful egghead course, I would like to add a feature to this utility repo.

I'm thinking of a function that determines if a date is today (something like [this](http://stackoverflow.com/questions/8393947/what-is-the-best-way-to-determine-if-a-date-is-today-in-javascript))

What do you think?

**Comment by kentcdodds** [comment]
Sounds perfect! I look forward to seeing the PR :)
