### ISSUE TITLE
Add search and replace function

### ISSUE THREAD

**Issue by ganes1410** [eggheadio-github/stack-overflow-copy-paste#74]
I just watched your  course on egghead and i want to add a search and replace function from here.
<a href="https://stackoverflow.com/questions/1144783/how-to-replace-all-occurrences-of-a-string-in-javascript/1144788#1144788"  target="_blank">Search and Replace</a>

can i do this ??

**Comment by kentcdodds** [comment]
Absolutely! Please do! :)
