### ISSUE TITLE
Add `toPower` function

### ISSUE THREAD

**Issue by brett-east** [eggheadio-github/stack-overflow-copy-paste#80]
Trying out my first contribution to an open source project.
Thinking that a 'toPower' function might be useful, although didn't see it as a StackOverflow answer.
Implementation as below:
```javascript
function toPower(num1, num2) {
  return num1**num2;
}
```

**Comment by kentcdodds** [comment]
Cool! I _believe_ that will work. I can't remember whether this project is set to transpile `**` I think it is though.

No worries about it not being stackoverflow specifically. Good luck!

**Comment by brett-east** [comment]
Okay, great! I will put something together now and submit a PR shortly 👍
