### ISSUE TITLE
Add method to initialize a prefilled array of given size

### ISSUE THREAD

**Issue by syonip** [eggheadio-github/stack-overflow-copy-paste#81]
Hello and thanks for your free series!
Trying out my first contribution.
My suggestion is a method similar to what's in array-fill.js, but will also initialize an array of a given size (does not need to receive the array as parameter).

Cheers!

**Comment by kentcdodds** [comment]
Sounds just fine! Thanks!

**Comment by kentcdodds** [comment]
Thank you for the contribution 🎉

**Comment by syonip** [comment]
Thanks a lot!
