### ISSUE TITLE
Add `endsWith` function

### ISSUE THREAD

**Issue by danielfsousa** [eggheadio-github/stack-overflow-copy-paste#90]
I know we can use this function in ES6, but we already have a `startsWith`function, so why not add an `endsWith` too?

Here is the implementation: http://stackoverflow.com/questions/280634/endswith-in-javascript

By the way, thank you for taking your time to create this awesome course! :smile:

**Comment by kentcdodds** [comment]
Sounds great! I'm looking forward to seeing your solution.
