### ISSUE TITLE
checkPalindrome function

### ISSUE THREAD

**Issue by jdrichardstech** [eggheadio-github/stack-overflow-copy-paste#95]
I am following your "How to Contribute to an Open Source Project on GitHub" on egghead.io and would like to add a checkPalindrome function that checks to see if the alphanumeric string that is left, after spaces and symbols have been removed, is a palindrome. This is my first attempt at trying to contribute to another repository. I was thinking I'd like to use the 2nd answer from: [https://stackoverflow.com/questions/41739845/freecodecamp-checking-for-palindromes](https://stackoverflow.com/questions/41739845/freecodecamp-checking-for-palindromes)

**Comment by kentcdodds** [comment]
Hi @jdrichardstech! Sounds awesome! I'm looking forward to seeing your solution :+1:

**Comment by kentcdodds** [comment]
Great job on #96
